<?php

/*
* Define plugin constants
*/

if ( ! defined( 'AS_DEFAULT_LOCATION' ) ) {
  define('AS_DEFAULT_LOCATION', '48.874746488384,2.2934013605118');
}

if ( ! defined( 'AS_ALL_REGIONS' )) {
  define('AS_ALL_REGIONS', [
    'africa' => 'Africa',
    'americas' => 'Americas',
    'apac' => 'Asia Pacific',
    'europe' => 'Europe',
    'middle_east' => 'Middle East'
  ]);
}

if ( ! defined( 'AS_ALL_COUNTRIES' )) {
  define('AS_ALL_COUNTRIES', [
    'afghanistan' => 'Afghanistan',
    'albania' => 'Albania',
    'algeria' => 'Algeria',
    'andorra' => 'Andorra',
    'angola' => 'Angola',
    'antigua_and_barbuda' => 'Antigua and Barbuda',
    'argentina' => 'Argentina',
    'armenia' => 'Armenia',
    'australia' => 'Australia',
    'austria' => 'Austria',
    'azerbaijan' => 'Azerbaijan',
    'bahamas' => 'Bahamas',
    'bahrain' => 'Bahrain',
    'bangladesh' => 'Bangladesh',
    'barbados' => 'Barbados',
    'belarus' => 'Belarus',
    'belgium' => 'Belgium',
    'belize' => 'Belize',
    'benin' => 'Benin',
    'bhutan' => 'Bhutan',
    'bolivia' => 'Bolivia',
    'bosnia_and_herzegovina' => 'Bosnia and Herzegovina',
    'botswana' => 'Botswana',
    'brazil' => 'Brazil',
    'brunei' => 'Brunei',
    'bulgaria' => 'Bulgaria',
    'burkina_faso' => 'Burkina Faso',
    'burundi' => 'Burundi',
    'cote_d_ivoire' => 'Côte d\'Ivoire',
    'cabo_verde' => 'Cabo Verde',
    'cambodia' => 'Cambodia',
    'cameroon' => 'Cameroon',
    'canada' => 'Canada',
    'central_african_republic' => 'Central African Republic',
    'chad' => 'Chad',
    'chile' => 'Chile',
    'china' => 'China',
    'colombia' => 'Colombia',
    'comoros' => 'Comoros',
    'congo' => 'Congo',
    'costa_rica' => 'Costa Rica',
    'croatia' => 'Croatia',
    'cuba' => 'Cuba',
    'cyprus' => 'Cyprus',
    'czech_republic' => 'Czech Republic',
    'democratic_republic_of_the_congo' => 'Democratic Republic of the Congo',
    'denmark' => 'Denmark',
    'djibouti' => 'Djibouti',
    'dominica' => 'Dominica',
    'dominican_republic' => 'Dominican Republic',
    'ecuador' => 'Ecuador',
    'egypt' => 'Egypt',
    'el_salvador' => 'El Salvador',
    'equatorial_guinea' => 'Equatorial Guinea',
    'eritrea' => 'Eritrea',
    'estonia' => 'Estonia',
    'eswatini' => 'Eswatini',
    'ethiopia' => 'Ethiopia',
    'fiji' => 'Fiji',
    'finland' => 'Finland',
    'france' => 'France',
    'gabon' => 'Gabon',
    'gambia' => 'Gambia',
    'georgia' => 'Georgia',
    'germany' => 'Germany',
    'ghana' => 'Ghana',
    'greece' => 'Greece',
    'grenada' => 'Grenada',
    'guatemala' => 'Guatemala',
    'guinea' => 'Guinea',
    'guinea_bissau' => 'Guinea-Bissau',
    'guyana' => 'Guyana',
    'haiti' => 'Haiti',
    'holy_see' => 'Holy See',
    'honduras' => 'Honduras',
    'hungary' => 'Hungary',
    'iceland' => 'Iceland',
    'india' => 'India',
    'indonesia' => 'Indonesia',
    'iran' => 'Iran',
    'iraq' => 'Iraq',
    'ireland' => 'Ireland',
    'israel' => 'Israel',
    'italy' => 'Italy',
    'jamaica' => 'Jamaica',
    'japan' => 'Japan',
    'jordan' => 'Jordan',
    'kazakhstan' => 'Kazakhstan',
    'kenya' => 'Kenya',
    'kiribati' => 'Kiribati',
    'kuwait' => 'Kuwait',
    'kyrgyzstan' => 'Kyrgyzstan',
    'laos' => 'Laos',
    'latvia' => 'Latvia',
    'lebanon' => 'Lebanon',
    'lesotho' => 'Lesotho',
    'liberia' => 'Liberia',
    'libya' => 'Libya',
    'liechtenstein' => 'Liechtenstein',
    'lithuania' => 'Lithuania',
    'luxembourg' => 'Luxembourg',
    'madagascar' => 'Madagascar',
    'malawi' => 'Malawi',
    'malaysia' => 'Malaysia',
    'maldives' => 'Maldives',
    'mali' => 'Mali',
    'malta' => 'Malta',
    'marshall_islands' => 'Marshall Islands',
    'mauritania' => 'Mauritania',
    'mauritius' => 'Mauritius',
    'mexico' => 'Mexico',
    'micronesia' => 'Micronesia',
    'moldova' => 'Moldova',
    'monaco' => 'Monaco',
    'mongolia' => 'Mongolia',
    'montenegro' => 'Montenegro',
    'morocco' => 'Morocco',
    'mozambique' => 'Mozambique',
    'myanmar' => 'Myanmar',
    'namibia' => 'Namibia',
    'nauru' => 'Nauru',
    'nepal' => 'Nepal',
    'netherlands' => 'Netherlands',
    'new_zealand' => 'New Zealand',
    'nicaragua' => 'Nicaragua',
    'niger' => 'Niger',
    'nigeria' => 'Nigeria',
    'north_korea' => 'North Korea',
    'north_macedonia' => 'North Macedonia',
    'norway' => 'Norway',
    'oman' => 'Oman',
    'pakistan' => 'Pakistan',
    'palau' => 'Palau',
    'palestine_state' => 'Palestine State',
    'papua_new_guinea' => 'Papua New Guinea',
    'paraguay' => 'Paraguay',
    'peru' => 'Peru',
    'philippines' => 'Philippines',
    'poland' => 'Poland',
    'portugal' => 'Portugal',
    'qatar' => 'Qatar',
    'romania' => 'Romania',
    'russia' => 'Russia',
    'rwanda' => 'Rwanda',
    'saint_kitts_and_nevis' => 'Saint Kitts and Nevis',
    'saint_lucia' => 'Saint Lucia',
    'saint_vincent_and_the_grenadines' => 'Saint Vincent and the Grenadines',
    'samoa' => 'Samoa',
    'san_marino' => 'San Marino',
    'sao_tome_and_principe' => 'Sao Tome and Principe',
    'saudi_arabia' => 'Saudi Arabia',
    'senegal' => 'Senegal',
    'serbia' => 'Serbia',
    'seychelles' => 'Seychelles',
    'sierra_leone' => 'Sierra Leone',
    'singapore' => 'Singapore',
    'slovakia' => 'Slovakia',
    'slovenia' => 'Slovenia',
    'solomon_islands' => 'Solomon Islands',
    'somalia' => 'Somalia',
    'south_africa' => 'South Africa',
    'south_korea' => 'South Korea',
    'south_sudan' => 'South Sudan',
    'spain' => 'Spain',
    'sri_lanka' => 'Sri Lanka',
    'sudan' => 'Sudan',
    'suriname' => 'Suriname',
    'sweden' => 'Sweden',
    'switzerland' => 'Switzerland',
    'syria' => 'Syria',
    'tajikistan' => 'Tajikistan',
    'tanzania' => 'Tanzania',
    'thailand' => 'Thailand',
    'timor_leste' => 'Timor-Leste',
    'togo' => 'Togo',
    'tonga' => 'Tonga',
    'trinidad_and_tobago' => 'Trinidad and Tobago',
    'tunisia' => 'Tunisia',
    'turkey' => 'Turkey',
    'turkmenistan' => 'Turkmenistan',
    'tuvalu' => 'Tuvalu',
    'uganda' => 'Uganda',
    'ukraine' => 'Ukraine',
    'united_arab_emirates' => 'United Arab Emirates',
    'united_kingdom' => 'United Kingdom',
    'united_states_of_america' => 'United States of America',
    'uruguay' => 'Uruguay',
    'uzbekistan' => 'Uzbekistan',
    'vanuatu' => 'Vanuatu',
    'venezuela' => 'Venezuela',
    'vietnam' => 'Vietnam',
    'yemen' => 'Yemen',
    'zambia' => 'Zambia',
    'zimbabwe' => 'Zimbabwe'
  ]);
}

if ( ! defined( 'AS_SITE_TO_COUNTRY_MAP' ) ) {
  define('AS_SITE_TO_COUNTRY_MAP', [
    'ae-en' => 'united_arab_emirates',
    'ar-es' => 'argentina',
    'at-de' => 'austria',
    'au-en' => 'australia',
    'be-en' => 'belgium',
    'br-pt' => 'brazil',
    'ca-en' => 'canada',
    'ca-fr' => 'canada',
    'ch-en' => 'switzerland',
    'cn-zh' => 'china',
    'co-es' => 'colombia',
    'cz-en' => 'czech_republic',
    'de-de' => 'germany',
    'dk-en' => 'denmark',
    'es-es' => 'spain',
    'fi-en' => 'finland',
    'fr-fr' => 'france',
    'gb-en' => 'united_kingdom',
    'hu-en' => 'hungary',
    'in-en' => 'india',
    'it-it' => 'italy',
    'jp-jp' => 'japan',
    'mx-es' => 'mexico',
    'nl-nl' => 'netherlands',
    'no-no' => 'norway',
    'pl-pl' => 'poland',
    'pt-en' => 'portugal',
    'ro-en' => 'romania',
    'sa-ar' => 'saudi_arabia',
    'se-en' => 'sweden',
    'sg-en' => 'singapore',
    'us-en' => 'united_states_of_america'
  ]);
}

if ( ! defined( 'AS_CODE_TO_COUNTRY_MAP' ) ) {
  define('AS_CODE_TO_COUNTRY_MAP', [
    'AE' => 'united_arab_emirates',
    'AU' => 'australia',
    'CN' => 'china',
    'PL' => 'poland',
    'FR' => 'france',
    'IN' => 'india',
    'GB' => 'united_kingdom',
    'AR' => 'argentina',
    'BR' => 'brazil',
    'CA' => 'canada',
    'CO' => 'colombia',
    'MX' => 'mexico',
    'US' => 'united_states_of_america',
    'AT' => 'austria',
    'BE' => 'belgium',
    'DK' => 'denmark',
    'FI' => 'finland',
    'JP' => 'japan',
    'CZ' => 'czech_republic',
    'SG' => 'singapore',
    'DE' => 'germany',
    'HU' => 'hungary',
    'IT' => 'italy',
    'NL' => 'netherlands',
    'NO' => 'norway',
    'PT' => 'portugal',
    'RO' => 'romania',
    'SA' => 'saudi_arabia',
    'ES' => 'spain',
    'SE' => 'sweden',
    'CH' => 'switzerland',
  ]);
}

/***********************************************************
DO NOT DELETE THIS SECTION
THIS IS USED SPECIFICALLY TO GENERATE TRANSLATIONS FORCEFULLY
************************************************************/
$translationValues = [
  __("Argentina", "cg-archive-shortcode"),
  __("Brazil", "cg-archive-shortcode"),
  __("Canada", "cg-archive-shortcode"),
  __("Mexico", "cg-archive-shortcode"),
  __("United States", "cg-archive-shortcode"),
  __("United States of America", "cg-archive-shortcode"),
  __("Colombia", "cg-archive-shortcode"),
  __("Australia", "cg-archive-shortcode"),
  __("China", "cg-archive-shortcode"),
  __("India", "cg-archive-shortcode"),
  __("Japan", "cg-archive-shortcode"),
  __("Singapore", "cg-archive-shortcode"),
  __("Austria", "cg-archive-shortcode"),
  __("Belgium", "cg-archive-shortcode"),
  __("Czech Republic", "cg-archive-shortcode"),
  __("Finland", "cg-archive-shortcode"),
  __("France", "cg-archive-shortcode"),
  __("Germany", "cg-archive-shortcode"),
  __("Hungary", "cg-archive-shortcode"),
  __("Italy", "cg-archive-shortcode"),
  __("Netherlands", "cg-archive-shortcode"),
  __("Norway", "cg-archive-shortcode"),
  __("Poland", "cg-archive-shortcode"),
  __("Portugal", "cg-archive-shortcode"),
  __("Romania", "cg-archive-shortcode"),
  __("Spain", "cg-archive-shortcode"),
  __("Sweden", "cg-archive-shortcode"),
  __("UK", "cg-archive-shortcode"),
  __("United Kingdom", "cg-archive-shortcode"),
  __("Denmark", "cg-archive-shortcode"),
  __("Switzerland", "cg-archive-shortcode"),
  __("Saudi Arabia", "cg-archive-shortcode"),
  __("UAE", "cg-archive-shortcode"),
  __("United Arab Emirates", "cg-archive-shortcode"),
];
